/**
* This file is auto-generated by Vite.
* Do not edit manually. Changes may be overwritten.
*/
const assets = [
  "B",
  "C",
  "G",
  "R",
  "U",
  "W",
  "account",
  "chevronDown",
  "close",
  "filter",
  "github",
  "google",
  "menu",
  "plusIcon",
  "share",
  "signOut",
  "trashBin"
] as const;
export type Assets = Record<typeof assets[number], string>;