/**
* This file is auto-generated by Vite.
* Do not edit manually. Changes may be overwritten.
*/
export { default as B } from './B.svg';
export { default as C } from './C.svg';
export { default as G } from './G.svg';
export { default as R } from './R.svg';
export { default as U } from './U.svg';
export { default as W } from './W.svg';
export { default as account } from './account.svg';
export { default as chevronDown } from './chevron-down.svg';
export { default as close } from './close.svg';
export { default as filter } from './filter.svg';
export { default as github } from './github.svg';
export { default as google } from './google.svg';
export { default as menu } from './menu.svg';
export { default as plusIcon } from './plus-icon.svg';
export { default as share } from './share.svg';
export { default as signOut } from './sign-out.svg';
export { default as trashBin } from './trash-bin.svg';